language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    - SYMFONY_VERSION="~2.8.0"

matrix:
    include:
        - php: 7.1
          env: VALIDATE_DOCS=true
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.1
          env: SYMFONY_VERSION="~3.3.0"
        - php: 7.2
          env: SYMFONY_VERSION="~3.4.0"
        - php: 7.1
          env: SYMFONY_VERSION="~2.8.0" WITH_LIIP_IMAGINE=true
        - php: 7.1
          env: SYMFONY_VERSION="~4.0.0" WITH_LIIP_IMAGINE=true
    allow_failures:
        - php: nightly

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || true
    - composer config platform.ext-mongo 1.6.14
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi
    - if [ "$WITH_LIIP_IMAGINE" = true ] ; then composer require --no-update liip/imagine-bundle:"^1.7|^2.0@dev"; fi;
    - if [ "$VALIDATE_DOCS" = true ]; then composer require --dev --no-update kphoen/rusty dev-master; fi

install: php -d memory_limit=-1 $(phpenv which composer) update $COMPOSER_FLAGS --no-suggest --prefer-dist

script:
    - if [ "$VALIDATE_DOCS" != true ]; then ./vendor/bin/phpunit; fi
    - if [ "$VALIDATE_DOCS" = true ]; then php ./vendor/bin/rusty check --no-execute ./Resources/doc; fi
