language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    - SYMFONY_VERSION="^4.4.0"
    - COMPOSER_FLAGS="--prefer-dist"

matrix:
    include:
        - php: 7.2
          env: VALIDATE_DOCS=true COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
          env: SYMFONY_VERSION="^4.4.0" WITH_LIIP_IMAGINE=true
        - php: 7.3
          env: SYMFONY_VERSION="^5.0.0"
    allow_failures:
        - php: nightly

before_install:
    - if [ -z "$(pecl list | grep -w mongodb)" ]; then pecl install mongodb-1.3.4; fi
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - phpenv config-rm xdebug.ini || true
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"; fi;
    - if [ "$WITH_LIIP_IMAGINE" = true ] ; then composer require --no-update liip/imagine-bundle:"^1.7|^2.0"; fi;
    - if [ "$VALIDATE_DOCS" = true ]; then composer require --dev --no-update kphoen/rusty dev-master; fi

install: php -d memory_limit=-1 $(phpenv which composer) update $COMPOSER_FLAGS --no-suggest

script:
    - if [ "$VALIDATE_DOCS" != true ]; then ./vendor/bin/phpunit; fi
    - if [ "$VALIDATE_DOCS" = true ]; then php ./vendor/bin/rusty check --no-execute ./docs; fi
