language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    - SYMFONY_VERSION="~2.8.0"

matrix:
    include:
        - php: 5.5
          env: SYMFONY_VERSION="~2.3.0"
        - php: 5.6
          env: SYMFONY_VERSION="~2.7.0"
        - php: 5.6
          env: SYMFONY_VERSION="~3.0.0"
        - php: 7.1
          env: SYMFONY_VERSION="~3.2.0"

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || true
    - composer config platform.ext-mongo 1.2.12
    - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
    - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then composer require --dev --no-update kphoen/rusty dev-master; fi

install: php -d memory_limit=-1 $(phpenv which composer) update --prefer-dist

script:
    - ./vendor/bin/phpunit
    - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then php ./vendor/bin/rusty check --no-execute ./Resources/doc; fi
