language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

sudo: false

env:
    - SYMFONY_VERSION="~2.3.0" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"
    - SYMFONY_VERSION="~2.5.0" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"
    - SYMFONY_VERSION="~2.6.0" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"
    - SYMFONY_VERSION="~2.7.0" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"

before_script:
    - phpenv config-rm xdebug.ini
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
    - composer require --no-update "doctrine/orm":"${DOCTRINE_VERSION}"
    - if [ "$TRAVIS_PHP_VERSION" = "5.3" ]; then composer remove --dev --no-update oneup/flysystem-bundle; fi
    - composer install --prefer-source

script: vendor/bin/phpunit
