os: linux
dist: focal
language: php

cache:
    directories:
        - $HOME/.composer/cache

env:
    - SYMFONY_VERSION="^4.4.0"
    - COMPOSER_FLAGS="--prefer-dist"
    - VALIDATE_DOCS=false
    - WITH_LIIP_IMAGINE=false

jobs:
    include:
        - php: 7.3
          env: VALIDATE_DOCS=true COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.4
          env: SYMFONY_VERSION="^4.4.0" WITH_LIIP_IMAGINE=true
        - php: 8.0snapshot
          env: VALIDATE_DOCS=false SYMFONY_VERSION="^5.2.0"

before_install:
    - if [ -z "$(pecl list | grep -w mongodb)" ]; then pecl install mongodb-1.8.0; fi
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - phpenv config-rm xdebug.ini || true
    - |
        if [ "$SYMFONY_VERSION" != "" ]; then
            sed -ri 's/"symfony\/(.+)": "(\^4\.[0-9]+\s*\|+\s*\^5\.[0-9]+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
        fi;
    - if [ "$WITH_LIIP_IMAGINE" = true ] ; then composer require --no-update liip/imagine-bundle:"^1.7|^2.0"; fi;
    - if [ "$VALIDATE_DOCS" != true ]; then composer remove --dev --no-update kphoen/rusty; fi

install: php -d memory_limit=-1 $(phpenv which composer) update $COMPOSER_FLAGS --no-suggest

script:
    - if [ "$VALIDATE_DOCS" != true ]; then ./vendor/bin/phpunit; fi
    - if [ "$VALIDATE_DOCS" = true ]; then php ./vendor/bin/rusty check --no-execute ./docs; fi
